name: Code Quality Checks
on:
  pull_request:
    branches: ['master']
    types: ['opened', 'reopened', 'synchronize', 'edited']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', 'go.mod', 'stable' ]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout source code

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        name: Setup Go ${{ matrix.go }}
        with:
          go-version: ${{ matrix.go != 'go.mod' && matrix.go || '' }}
          go-version-file: ${{ matrix.go == 'go.mod' && matrix.go || '' }}

      - name: Build Go
        run: go build -v ./...

      - name: Test Go
        run: go test -race ./... -v
